@extends('layouts.public')
@section('title', 'Avinto Project - Web, Mobile & Digital Product Studio')
@section('content')
@php($portfolio = config('portfolio'))
<section class="hero avinto-hero has-ambient">
    @include('partials.ambient-shapes', ['variant' => 'sparse'])
    <div class="container hero-grid">
        <div class="hero-copy reveal"><span class="hero-badge"><i data-lucide="sparkles" size="15"></i> Fast, elegant, affordable</span><h1>Web & aplikasi,<br><span class="text-gradient">beres lebih cepat.</span></h1><p>Avinto Project membantu ide bisnis, tugas, dan operasional jadi produk digital yang rapi, modern, dan ramah budget.</p><div class="hero-actions"><a class="btn btn-primary" href="{{ route('orders.create') }}">Wujudkan ide sekarang <i data-lucide="arrow-right" size="17"></i></a><a class="btn btn-soft" href="{{ route('projects.index') }}"><i data-lucide="panels-top-left" size="17"></i> Lihat hasil nyata</a></div><div class="hero-trust"><span><i data-lucide="zap" size="16"></i> Proses lebih cepat</span><span><i data-lucide="gem" size="16"></i> Desain elegan</span><span><i data-lucide="badge-dollar-sign" size="16"></i> Biaya bersahabat</span></div></div>
        <div class="hero-visual avinto-visual reveal"><div class="hero-portrait-shell"><img src="/assets/portfolio/hero.png" alt="Paris Alvito - Fullstack Developer"><div class="hero-code-card"><span>Paris Alvito</span><strong>{{ $portfolio['headline'] }}</strong></div></div><div class="float-card one"><i data-lucide="check-circle-2" size="16"></i> 35+ project delivered</div><div class="float-card two"><i data-lucide="map-pin" size="16"></i> Medan, Indonesia</div></div>
    </div>
</section>

<section class="section-sm metrics-showcase"><div class="metrics-glow one"></div><div class="metrics-glow two"></div><div class="container"><div class="stats-strip reveal"><div class="stats-intro"><span><i data-lucide="rocket" size="15"></i> Built through real work</span><small>Pengalaman lintas institusi, bisnis, dan produk independen.</small></div><div class="stats-grid">@foreach($portfolio['stats'] as $stat)<div class="stat-item"><span class="stat-icon"><i data-lucide="{{ ['layers-3','building-2','calendar-range','github'][$loop->index] }}" size="20"></i></span><div><div class="stat-value">{{ $stat['value'] }}</div><div class="stat-label">{{ $stat['label'] }}</div></div><i class="stat-spark"></i></div>@endforeach</div></div></div></section>

<section class="section surface-section" id="tentang"><div class="container split-card card reveal avinto-intro"><div class="content"><span class="section-kicker">Meet the builder</span><h2 class="section-title">Teknologi, desain, dan bisnis dalam satu perspektif.</h2><p class="section-lead">{{ $portfolio['profile'] }}</p><div class="hero-actions"><a class="btn btn-primary" href="{{ route('profile') }}">Lihat perjalanan saya</a><a class="btn btn-soft" href="/assets/portfolio/CV_Paris_Alvito.pdf" target="_blank"><i data-lucide="download" size="17"></i> Unduh CV</a></div></div><div class="visual skill-cloud"><div class="skill-orbit"><span>Laravel</span><span>React</span><span>Flutter</span><span>Go</span><span>Docker</span><span>Cloudflare</span><div class="skill-core"><i data-lucide="braces" size="40"></i><strong>Build</strong></div></div></div></div></section>

<section class="section digital-footprint-section has-ambient">
    @include('partials.ambient-shapes', ['variant' => 'center'])
    <div class="container">
        <div class="section-heading-row reveal"><div><span class="section-kicker">Digital footprint</span><h2 class="section-title">Kode, kreativitas, dan eksperimen AI.</h2><p class="section-lead">Bukan hanya hasil akhir. Ini adalah jejak proses belajar, membangun, dan mengeksplorasi cara baru menciptakan produk digital.</p></div><a class="btn btn-outline" href="{{ $portfolio['contact']['github'] }}" target="_blank" rel="noopener"><i data-lucide="github"></i> Buka GitHub</a></div>
        <div class="github-showcase card reveal"><div class="github-window-bar"><span></span><span></span><span></span><small>github.com/AlvinAlvito</small></div><a href="{{ $portfolio['contact']['github'] }}" target="_blank" rel="noopener"><img src="/assets/portfolio/showcase/github.png" alt="Profil dan aktivitas GitHub Alvin Alvito" loading="lazy"></a><div class="github-caption"><div><span class="section-kicker">Open source activity</span><h3>25 repositori publik dan terus bertumbuh.</h3></div><span class="github-live"><i></i> Active builder</span></div></div>
        <div class="ai-showcase reveal"><div class="ai-showcase-copy"><span class="section-kicker">AI visual exploration</span><h3>Teknologi juga bisa terasa personal.</h3><p>Serangkaian visual berbasis AI yang menggambarkan cara saya bekerja: mendengar kebutuhan, berdiskusi, lalu mengubah ide menjadi solusi yang dapat digunakan.</p><div class="tech-list"><span>Human-centered</span><span>AI-assisted</span><span>Built with purpose</span></div></div><div class="ai-collage"><figure class="ai-frame ai-frame-main"><img src="/assets/portfolio/showcase/ai-collaboration.png" alt="Visual AI kolaborasi pengembangan produk" loading="lazy"></figure><figure class="ai-frame ai-frame-top"><img src="/assets/portfolio/showcase/ai-consultation.png" alt="Visual AI konsultasi teknologi" loading="lazy"></figure><figure class="ai-frame ai-frame-bottom"><img src="/assets/portfolio/showcase/ai-workspace.png" alt="Visual AI diskusi di ruang kerja" loading="lazy"></figure></div></div>
    </div>
</section>

<section class="section has-ambient" id="layanan">@include('partials.ambient-shapes', ['variant' => 'right'])<div class="container"><div class="section-heading-row reveal"><div><span class="section-kicker">Layanan</span><h2 class="section-title">Dari ide sampai siap digunakan.</h2><p class="section-lead">Satu partner untuk desain, pengembangan, deployment, dan pengembangan lanjutan.</p></div><a class="btn btn-outline" href="{{ route('orders.create') }}">Minta estimasi</a></div><div class="service-grid">@foreach($portfolio['services'] as $service)<article class="card feature-card service-card reveal"><div class="icon-box"><i data-lucide="{{ $service['icon'] }}"></i></div><h3>{{ $service['title'] }}</h3><p>{{ $service['description'] }}</p><div class="service-price">{{ $service['price'] }}</div></article>@endforeach</div></div></section>

<section class="section surface-section"><div class="container"><div class="section-heading-row reveal"><div><span class="section-kicker">Selected work</span><h2 class="section-title">Karya yang memecahkan masalah nyata.</h2><p class="section-lead">Beberapa produk untuk pendidikan, operasional institusi, layanan publik, dan bisnis.</p></div><a class="link-arrow" href="{{ route('projects.index') }}">Lihat seluruh proyek <i data-lucide="arrow-right" size="16"></i></a></div><div class="project-grid">@forelse($featuredProjects as $project)@include('partials.project-card', compact('project'))@empty<div class="card empty-state"><p>Data proyek sedang disiapkan.</p></div>@endforelse</div></div></section>

<section class="section"><div class="container"><div class="grid-2 experience-preview"><div class="reveal"><span class="section-kicker">Cara bekerja</span><h2 class="section-title">Kolaborasi yang rapi dari awal.</h2><p class="section-lead">Setiap produk dimulai dari memahami masalah, bukan langsung menulis kode.</p><div class="process-list">@foreach([['01','Discovery','Memetakan tujuan, pengguna, ruang lingkup, dan prioritas.'],['02','Design & Build','Merancang pengalaman lalu membangun secara iteratif.'],['03','Test & Launch','Menguji, menyiapkan deployment, dan memastikan handover jelas.'],['04','Grow','Maintenance dan pengembangan lanjutan berdasarkan kebutuhan.']] as $step)<div class="process-item"><span>{{ $step[0] }}</span><div><h3>{{ $step[1] }}</h3><p>{{ $step[2] }}</p></div></div>@endforeach</div></div><div class="reveal"><div class="card leadership-card"><span class="section-kicker">Leadership</span><h3>Teknis yang tetap selaras dengan bisnis.</h3>@foreach($portfolio['leadership'] as $item)<div class="leadership-item"><div><strong>{{ $item['role'] }} - {{ $item['company'] }}</strong><small>{{ $item['period'] }}</small></div><p>{{ $item['description'] }}</p></div>@endforeach</div></div></div></div></section>

<section class="section surface-section"><div class="container"><div class="reveal"><span class="section-kicker">Testimoni</span><h2 class="section-title">Dipercaya dalam kolaborasi nyata.</h2></div><div class="grid-3 testimonial-grid">@foreach($portfolio['testimonials'] as $item)<article class="card testimonial-card reveal"><i data-lucide="quote" class="quote-icon"></i><p>“{{ $item['quote'] }}”</p><div class="testimonial-person"><img src="{{ $item['image'] }}" alt="{{ $item['name'] }}"><div><strong>{{ $item['name'] }}</strong><small>{{ $item['role'] }}</small></div></div></article>@endforeach</div></div></section>

<section class="section avinto-cta"><div class="container"><div class="cta-card reveal"><div><span class="section-kicker">Punya ide?</span><h2>Mari jadikan konsep Anda produk yang bisa digunakan.</h2><p>Ceritakan kebutuhan, target, dan kisaran budget. Saya akan menghubungi Anda untuk membahas arah terbaiknya.</p></div><div class="hero-actions"><a class="btn btn-light" href="{{ route('orders.create') }}">Mulai proyek sekarang <i data-lucide="arrow-up-right"></i></a><a class="btn btn-ghost-light" target="_blank" href="https://wa.me/{{ $portfolio['contact']['whatsapp'] }}">WhatsApp</a></div></div></div></section>
@endsection
