@extends('layouts.public')
@section('title', 'Tentang Paris Alvito - Avinto Project')
@section('content')
@php($portfolio = config('portfolio'))
<section class="page-hero has-ambient">@include('partials.ambient-shapes', ['variant' => 'sparse'])<div class="container reveal"><div class="breadcrumbs"><a href="{{ route('home') }}">Beranda</a><span>/</span><span>Tentang</span></div><span class="section-kicker">Paris Alvito / Alvin Alvito</span><h1 class="section-title">Engineer yang nyaman berbicara<br>dengan kode maupun bisnis.</h1><p>{{ $portfolio['profile'] }}</p><div class="hero-actions"><a class="btn btn-primary" href="{{ route('orders.create') }}">Bekerja bersama saya</a><a class="btn btn-soft" href="/assets/portfolio/CV_Paris_Alvito.pdf" target="_blank"><i data-lucide="file-down"></i> Lihat CV</a></div></div></section>

<section class="section"><div class="container profile-feature"><div class="profile-photo-card reveal"><img src="/assets/portfolio/hero.png" alt="Paris Alvito"><div><strong>{{ $portfolio['headline'] }}</strong><span>{{ $portfolio['contact']['location'] }}</span></div></div><div class="reveal"><span class="section-kicker">Core expertise</span><h2 class="section-title">Full-stack dalam arti yang sesungguhnya.</h2><p class="section-lead">Terbiasa bergerak dari diskusi stakeholder, desain arsitektur, antarmuka, backend, database, integrasi, pengujian, deployment, hingga maintenance.</p><div class="skill-groups">@foreach($portfolio['skills'] as $group => $skills)<div><h3>{{ $group }}</h3><div class="tech-list">@foreach($skills as $skill)<span>{{ $skill }}</span>@endforeach</div></div>@endforeach</div></div></div></section>

<section class="section surface-section journey-section"><div class="container journey-layout"><div class="journey-intro reveal"><span class="section-kicker">Professional journey</span><h2 class="section-title">Bertumbuh lewat tanggung jawab yang nyata.</h2><p class="section-lead">Dari laboratorium kampus hingga memimpin divisi IT, setiap peran membentuk cara saya membangun teknologi: terukur, komunikatif, dan bertanggung jawab sampai produk digunakan.</p><div class="journey-summary"><div><strong>7+</strong><span>Tahun berkarya</span></div><div><strong>35+</strong><span>Proyek selesai</span></div><div><strong>3</strong><span>Peran leadership</span></div></div></div><div class="journey-list">@foreach($portfolio['experiences'] as $experience)<article class="journey-card reveal"><div class="journey-card-top"><span class="journey-number">{{ str_pad($loop->iteration, 2, '0', STR_PAD_LEFT) }}</span><span class="journey-period"><i data-lucide="calendar-days"></i> {{ $experience['period'] }}</span>@if($loop->first)<span class="journey-current"><i></i> Current role</span>@endif</div><div class="journey-company">{{ $experience['company'] }}</div><h3>{{ $experience['role'] }}</h3><p>{{ $experience['description'] }}</p></article>@endforeach</div></div></section>

<section class="section"><div class="container grid-2"><div class="reveal"><span class="section-kicker">Pendidikan</span><h2 class="section-title">Fondasi akademik.</h2>@foreach($portfolio['education'] as $item)<div class="card education-card"><span>{{ $item['period'] }}</span><h3>{{ $item['degree'] }}</h3><p>{{ $item['school'] }}</p></div>@endforeach</div><div class="reveal"><span class="section-kicker">Professional strengths</span><h2 class="section-title">Lebih dari kemampuan teknis.</h2><div class="strength-grid">@foreach(['Kepemimpinan tim','Stakeholder communication','Problem solving','Kolaborasi lintas fungsi','Adaptasi cepat','Product ownership'] as $strength)<div class="card strength-card"><i data-lucide="check"></i><span>{{ $strength }}</span></div>@endforeach</div></div></div></section>

<section class="section avinto-cta"><div class="container"><div class="cta-card reveal"><div><span class="section-kicker">Next collaboration</span><h2>Ada tantangan digital yang perlu diselesaikan?</h2><p>Mari diskusikan konteksnya dan cari pendekatan yang realistis.</p></div><a class="btn btn-light" href="{{ route('orders.create') }}">Ceritakan kebutuhan Anda</a></div></div></section>
@endsection
