@extends('layouts.public')
@section('title', $project->title.' - Avinto Project')
@section('content')
<section class="page-hero project-detail-hero"><div class="container reveal"><div class="breadcrumbs"><a href="{{ route('home') }}">Beranda</a><span>/</span><a href="{{ route('projects.index') }}">Proyek</a><span>/</span><span>{{ $project->title }}</span></div><span class="section-kicker">{{ $project->category }}</span><h1 class="section-title">{{ $project->title }}</h1><p>{{ $project->summary }}</p><div class="tech-list">@foreach($project->technologies ?? [] as $tech)<span>{{ $tech }}</span>@endforeach</div></div></section>
<section class="section project-story"><div class="container"><div class="project-detail-grid"><div class="project-gallery reveal"><button class="gallery-main" type="button" data-gallery-index="0"><img id="galleryMainImage" src="{{ $project->cover_image }}" alt="Tampilan {{ $project->title }}"></button>@if(count($project->images ?? []) > 1)<div class="gallery-thumbs">@foreach($project->images as $image)<button type="button" class="{{ $loop->first ? 'active' : '' }}" data-gallery-thumb="{{ $loop->index }}"><img src="{{ $image }}" alt="Screenshot {{ $loop->iteration }} {{ $project->title }}"></button>@endforeach</div>@endif</div><aside class="card project-facts reveal"><span class="section-kicker">Project details</span><div><small>Klien / pemilik</small><strong>{{ $project->client ?: 'Proyek independen' }}</strong></div><div><small>Tahun</small><strong>{{ $project->year ?: '-' }}</strong></div><div><small>Status</small><strong>{{ ['completed'=>'Selesai','ongoing'=>'Sedang dikembangkan','concept'=>'Konsep'][$project->status] ?? $project->status }}</strong></div>@if($project->project_url)<a class="btn btn-primary" href="{{ $project->project_url }}" target="_blank" rel="noopener">Kunjungi proyek <i data-lucide="external-link"></i></a>@endif @if($project->repository_url)<a class="btn btn-soft" href="{{ $project->repository_url }}" target="_blank" rel="noopener"><i data-lucide="github"></i> Repository</a>@endif</aside></div><div class="project-description reveal"><span class="section-kicker">Tentang proyek</span><h2 class="section-title">Dibangun untuk kebutuhan yang nyata.</h2><p>{!! nl2br(e($project->description ?: $project->summary)) !!}</p></div></div></section>
@if($related->isNotEmpty())<section class="section surface-section"><div class="container"><div class="section-heading-row"><div><span class="section-kicker">Related work</span><h2 class="section-title">Proyek lain yang sejenis.</h2></div></div><div class="project-grid">@foreach($related as $project)@include('partials.project-card', compact('project'))@endforeach</div></div></section>@endif
<section class="section avinto-cta"><div class="container"><div class="cta-card reveal"><div><span class="section-kicker">Build yours</span><h2>Ingin produk dengan kualitas serupa?</h2><p>Ceritakan konteks dan target Anda, lalu kita susun langkah berikutnya.</p></div><a class="btn btn-light" href="{{ route('orders.create') }}">Mulai konsultasi</a></div></div></section>
@push('scripts')<script>document.querySelectorAll('[data-gallery-thumb]').forEach((button)=>button.addEventListener('click',()=>{document.getElementById('galleryMainImage').src=button.querySelector('img').src;document.querySelectorAll('[data-gallery-thumb]').forEach(item=>item.classList.remove('active'));button.classList.add('active');}));</script>@endpush
@endsection
