@extends('layouts.main')
@section('title','Overview')
@section('page-title','Business Overview')
@section('content')
<div class="admin-heading"><div><h2>Selamat datang, Alvin.</h2><p>Pantau portofolio dan calon proyek baru dari satu workspace.</p></div><a class="btn btn-primary" href="{{ route('admin.projects.index', ['modal' => 'create']) }}"><i data-lucide="plus" size="17"></i> Tambah proyek</a></div>
<div class="metric-grid"><div class="metric-card"><span class="metric-icon"><i data-lucide="panels-top-left"></i></span><div><strong>{{ $summary['projects'] }}</strong><small>Total proyek</small></div></div><div class="metric-card"><span class="metric-icon"><i data-lucide="eye"></i></span><div><strong>{{ $summary['published'] }}</strong><small>Proyek tayang</small></div></div><div class="metric-card"><span class="metric-icon"><i data-lucide="inbox"></i></span><div><strong>{{ $summary['orders'] }}</strong><small>Total permintaan</small></div></div><div class="metric-card"><span class="metric-icon"><i data-lucide="bell-ring"></i></span><div><strong>{{ $summary['new_orders'] }}</strong><small>Belum ditindaklanjuti</small></div></div></div>
<div class="dashboard-grid"><section class="data-card chart-card"><div class="data-card-head"><div><h3>Tren permintaan</h3><small>Enam bulan terakhir</small></div></div><div id="orderTrendChart"></div></section><section class="data-card chart-card"><div class="data-card-head"><div><h3>Pipeline klien</h3><small>Status seluruh permintaan</small></div></div><div id="orderStatusChart"></div></section></div>
<div class="dashboard-grid admin-lists"><section class="data-card"><div class="data-card-head"><div><h3>Permintaan terbaru</h3><small>Calon proyek yang baru masuk</small></div><a class="link-arrow" href="{{ route('admin.orders.index') }}">Lihat semua</a></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Klien</th><th>Proyek</th><th>Budget</th><th>Status</th><th></th></tr></thead><tbody>@forelse($recentOrders as $order)<tr><td><div class="person-cell"><span class="person-avatar">{{ strtoupper(mb_substr($order->name,0,1)) }}</span><div><strong>{{ $order->name }}</strong><small>{{ $order->created_at->diffForHumans() }}</small></div></div></td><td>{{ $order->project_type }}</td><td>{{ $order->budget_range }}</td><td><span class="status-badge order-status-{{ $order->status }}">{{ $statusLabels[$order->status] ?? $order->status }}</span></td><td><a class="btn btn-soft btn-sm btn-icon" href="{{ route('admin.orders.show',$order) }}"><i data-lucide="arrow-up-right"></i></a></td></tr>@empty<tr><td colspan="5"><div class="empty-state"><p>Belum ada permintaan proyek.</p></div></td></tr>@endforelse</tbody></table></div></section><section class="data-card"><div class="data-card-head"><div><h3>Proyek terbaru</h3><small>Konten portofolio</small></div><a class="link-arrow" href="{{ route('admin.projects.index') }}">Kelola</a></div><div class="admin-project-list">@foreach($recentProjects as $project)<a href="{{ route('admin.projects.index', ['modal' => 'edit-'.$project->id]) }}"><img src="{{ $project->cover_image }}" alt=""><div><strong>{{ $project->title }}</strong><small>{{ $project->category }} - {{ $project->is_published ? 'Tayang' : 'Draft' }}</small></div><i data-lucide="chevron-right"></i></a>@endforeach</div></section></div>
@endsection
@push('head')<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>@endpush
@push('scripts')<script>const base={chart:{fontFamily:'Plus Jakarta Sans',toolbar:{show:false}},dataLabels:{enabled:false},grid:{borderColor:'#eee8f8'},colors:['#7651c5']};new ApexCharts(document.querySelector('#orderTrendChart'),{...base,chart:{...base.chart,type:'area',height:300},series:[{name:'Permintaan',data:@json($orderTrendChart['series'])}],xaxis:{categories:@json($orderTrendChart['labels'])},stroke:{curve:'smooth',width:3},fill:{type:'gradient',gradient:{opacityFrom:.35,opacityTo:.04}}}).render();new ApexCharts(document.querySelector('#orderStatusChart'),{...base,chart:{...base.chart,type:'donut',height:300},series:@json($orderStatusChart['series']),labels:@json($orderStatusChart['labels']),colors:['#7651c5','#38a3a5','#e0a82e','#4f7cff','#24ad7b','#db5470'],legend:{position:'bottom'},plotOptions:{pie:{donut:{size:'68%'}}}}).render();</script>@endpush
