@extends('layouts.main')
@section('title','Permintaan Klien')
@section('page-title','Client Inquiries')
@section('content')
@php($statusLabels=['new'=>'Baru','contacted'=>'Dihubungi','discussion'=>'Diskusi','in_progress'=>'Dikerjakan','completed'=>'Selesai','cancelled'=>'Dibatalkan'])
<div class="admin-heading"><div><h2>Pipeline calon proyek</h2><p>Kelola setiap inquiry dari kontak awal sampai proyek selesai.</p></div></div>@if(session('success'))<div class="flash-success">{{ session('success') }}</div>@endif
<form class="filter-panel" method="GET"><div class="filter-grid"><div class="field"><label>Pencarian</label><input class="input" name="q" value="{{ $filters['q'] ?? '' }}" placeholder="Nama, nomor HP, organisasi..."></div><div class="field"><label>Status</label><select class="select" name="status"><option value="">Semua status</option>@foreach($statusLabels as $value=>$label)<option value="{{ $value }}" @selected(($filters['status']??'')===$value)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Jenis proyek</label><select class="select" name="project_type"><option value="">Semua jenis</option>@foreach($projectTypes as $type)<option @selected(($filters['project_type']??'')===$type)>{{ $type }}</option>@endforeach</select></div><div class="filter-submit"><button class="btn btn-primary"><i data-lucide="search"></i> Terapkan</button><a class="btn btn-soft btn-icon" href="{{ route('admin.orders.index') }}"><i data-lucide="rotate-ccw"></i></a></div></div></form>
<div class="data-card"><div class="data-card-head"><div><h3>{{ $orders->total() }} permintaan</h3><small>Urut dari inquiry terbaru</small></div></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Calon klien</th><th>Jenis proyek</th><th>Budget</th><th>Target</th><th>Status</th><th>Masuk</th><th>Aksi</th></tr></thead><tbody>@forelse($orders as $order)<tr class="{{ $order->status==='new' ? 'row-highlight' : '' }}"><td><div class="person-cell"><span class="person-avatar">{{ strtoupper(mb_substr($order->name,0,1)) }}</span><div><strong>{{ $order->name }}</strong><small>{{ $order->organization ?: $order->phone }}</small></div></div></td><td>{{ $order->project_type }}</td><td>{{ $order->budget_range }}</td><td>{{ optional($order->desired_deadline)->format('d M Y') ?: 'Fleksibel' }}</td><td><span class="status-badge order-status-{{ $order->status }}">{{ $statusLabels[$order->status] ?? $order->status }}</span></td><td>{{ $order->created_at->format('d M Y, H:i') }}</td><td><a class="btn btn-soft btn-sm" href="{{ route('admin.orders.show',$order) }}">Buka <i data-lucide="arrow-up-right"></i></a></td></tr>@empty<tr><td colspan="7"><div class="empty-state"><i data-lucide="inbox"></i><p>Belum ada permintaan yang sesuai.</p></div></td></tr>@endforelse</tbody></table></div>@if($orders->hasPages())<div class="pagination-shell admin-pagination-wrap">{{ $orders->onEachSide(1)->links('vendor.pagination.admin') }}</div>@endif</div>
@endsection
