@extends('layouts.main')
@section('title','Detail Permintaan')
@section('page-title','Inquiry #'.$order->id)
@section('content')
@php($statusLabels=['new'=>'Baru','contacted'=>'Dihubungi','discussion'=>'Diskusi','in_progress'=>'Dikerjakan','completed'=>'Selesai','cancelled'=>'Dibatalkan'])
<div class="admin-heading"><div><h2>{{ $order->project_type }}</h2><p>Dikirim {{ $order->created_at->translatedFormat('d F Y, H:i') }} dari {{ $order->source }}.</p></div><a class="btn btn-soft" href="{{ route('admin.orders.index') }}"><i data-lucide="arrow-left"></i> Kembali</a></div>@if(session('success'))<div class="flash-success">{{ session('success') }}</div>@endif
<div class="order-admin-grid"><div class="form-stack"><section class="data-card order-detail-card"><div class="data-card-head"><div><h3>Informasi calon klien</h3><small>Kontak dan organisasi</small></div><span class="status-badge order-status-{{ $order->status }}">{{ $statusLabels[$order->status] }}</span></div><div class="detail-grid"><div><small>Nama</small><strong>{{ $order->name }}</strong></div><div><small>Organisasi</small><strong>{{ $order->organization ?: '-' }}</strong></div><div><small>Nomor HP</small><a href="https://wa.me/{{ preg_replace('/\D/','',$order->phone) }}" target="_blank">{{ $order->phone }}</a></div><div><small>Email</small><a href="mailto:{{ $order->email }}">{{ $order->email ?: '-' }}</a></div><div><small>Preferensi kontak</small><strong>{{ ucfirst($order->contact_preference) }}</strong></div><div><small>Target selesai</small><strong>{{ optional($order->desired_deadline)->translatedFormat('d F Y') ?: 'Fleksibel' }}</strong></div></div></section><section class="data-card order-detail-card"><div class="data-card-head"><div><h3>Brief proyek</h3><small>{{ $order->budget_range }}</small></div></div><div class="brief-content">{!! nl2br(e($order->details)) !!}</div></section></div>
<aside><section class="data-card editor-section sticky-admin-card"><div class="data-card-head"><h3>Tindak lanjut</h3></div><form class="form-stack editor-body" method="POST" action="{{ route('admin.orders.update',$order) }}">@csrf @method('PUT')<div class="field"><label>Status pipeline</label><select class="select" name="status">@foreach($statusLabels as $value=>$label)<option value="{{ $value }}" @selected($order->status===$value)>{{ $label }}</option>@endforeach</select></div><div class="field"><label>Catatan internal</label><textarea class="input textarea" name="admin_notes" rows="8" placeholder="Hasil kontak, kebutuhan tambahan, estimasi...">{{ old('admin_notes',$order->admin_notes) }}</textarea></div><button class="btn btn-primary"><i data-lucide="save"></i> Simpan perubahan</button><a class="btn btn-soft" href="https://wa.me/{{ preg_replace('/\D/','',$order->phone) }}?text={{ urlencode('Halo '.$order->name.', saya Alvin dari Avinto Project. Terima kasih sudah mengirimkan detail proyek Anda.') }}" target="_blank"><i data-lucide="message-circle"></i> Hubungi via WhatsApp</a></form><form class="editor-body" method="POST" action="{{ route('admin.orders.destroy',$order) }}" onsubmit="return confirm('Hapus permintaan ini secara permanen?')">@csrf @method('DELETE')<button class="btn btn-danger-soft" style="width:100%"><i data-lucide="trash-2"></i> Hapus permintaan</button></form></section></aside></div>
@endsection
