@extends('layouts.public')
@section('title', 'Mulai Proyek - Avinto Project')
@section('content')
@php($contact = config('portfolio.contact'))
<section class="page-hero order-hero"><div class="container reveal"><div class="breadcrumbs"><a href="{{ route('home') }}">Beranda</a><span>/</span><span>Mulai Proyek</span></div><span class="section-kicker">Project inquiry</span><h1 class="section-title">Ceritakan apa yang ingin<br>Anda bangun.</h1><p>Semakin jelas konteksnya, semakin tepat arah awal yang bisa kami rekomendasikan.</p></div></section>
<section class="section order-section"><div class="container order-layout"><aside class="reveal"><div class="card order-info"><span class="section-kicker">Sebelum mengirim</span><h2>Yang terjadi selanjutnya.</h2>@foreach([['message-square','Review kebutuhan','Detail Anda akan dipelajari untuk memahami ruang lingkup awal.'],['phone-call','Diskusi singkat','Kami menghubungi Anda melalui kanal pilihan untuk melengkapi konteks.'],['file-check-2','Estimasi & arah kerja','Anda menerima rekomendasi solusi, estimasi biaya, dan langkah pengerjaan.']] as $step)<div class="order-step"><span><i data-lucide="{{ $step[0] }}"></i></span><div><strong>{{ $step[1] }}</strong><p>{{ $step[2] }}</p></div></div>@endforeach<div class="direct-contact"><small>Lebih nyaman bicara langsung?</small><a href="https://wa.me/{{ $contact['whatsapp'] }}" target="_blank"><i data-lucide="message-circle"></i> {{ $contact['phone'] }}</a></div></div></aside><div class="card inquiry-card reveal"><form class="form-stack" method="POST" action="{{ route('orders.store') }}">@csrf
    @if($errors->any())<div class="form-error"><strong>Mohon periksa kembali formulir.</strong><br>{{ $errors->first() }}</div>@endif
    <div class="form-grid"><div class="field"><label for="name">Nama lengkap *</label><input class="input" id="name" name="name" value="{{ old('name') }}" required placeholder="Nama Anda"></div><div class="field"><label for="phone">Nomor WhatsApp / HP *</label><input class="input" id="phone" name="phone" value="{{ old('phone') }}" required placeholder="08xxxxxxxxxx"></div></div>
    <div class="form-grid"><div class="field"><label for="email">Email</label><input class="input" type="email" id="email" name="email" value="{{ old('email') }}" placeholder="nama@email.com"></div><div class="field"><label for="organization">Perusahaan / organisasi</label><input class="input" id="organization" name="organization" value="{{ old('organization') }}" placeholder="Opsional"></div></div>
    <div class="form-grid"><div class="field"><label for="project_type">Jenis proyek *</label><select class="select" id="project_type" name="project_type" required><option value="">Pilih jenis proyek</option>@foreach(['Website Perusahaan','Sistem Informasi / Dashboard','E-commerce','Aplikasi Mobile','UI/UX Design','API / Backend','IT Support & Infrastructure','Lainnya'] as $type)<option @selected(old('project_type')===$type)>{{ $type }}</option>@endforeach</select></div><div class="field"><label for="budget_range">Kisaran budget *</label><select class="select" id="budget_range" name="budget_range" required><option value="">Pilih kisaran</option>@foreach(['Di bawah Rp1 juta','Rp1 - 3 juta','Rp3 - 7 juta','Rp7 - 15 juta','Rp15 - 30 juta','Di atas Rp30 juta','Perlu didiskusikan'] as $budget)<option @selected(old('budget_range')===$budget)>{{ $budget }}</option>@endforeach</select></div></div>
    <div class="field"><label for="details">Detail kebutuhan *</label><textarea class="input textarea" id="details" name="details" rows="7" required placeholder="Ceritakan tujuan proyek, pengguna, fitur utama, masalah yang ingin diselesaikan, dan referensi bila ada...">{{ old('details') }}</textarea><small>Minimal 20 karakter. Hindari mencantumkan password atau data rahasia.</small></div>
    <div class="form-grid"><div class="field"><label for="desired_deadline">Target selesai</label><input class="input" type="date" min="{{ now()->toDateString() }}" id="desired_deadline" name="desired_deadline" value="{{ old('desired_deadline') }}"></div><div class="field"><label for="contact_preference">Preferensi dihubungi *</label><select class="select" id="contact_preference" name="contact_preference" required><option value="whatsapp" @selected(old('contact_preference','whatsapp')==='whatsapp')>WhatsApp</option><option value="phone" @selected(old('contact_preference')==='phone')>Telepon</option><option value="email" @selected(old('contact_preference')==='email')>Email</option></select></div></div>
    <button class="btn btn-primary btn-submit-order" type="submit">Kirim permintaan proyek <i data-lucide="send"></i></button><p class="form-consent"><i data-lucide="shield-check"></i> Data hanya digunakan untuk menindaklanjuti permintaan Anda.</p>
</form></div></div></section>
@endsection
